### ISSUE TITLE
Rollup Error on yarn

### ISSUE THREAD

**Issue by jpaulomotta** [ianmcnally/react-currency-masked-input#39]
Hello,

This component works amazingly. We are using it in production. Thank you for publishing it.

I've forked the repository to see if I could work on a fix to format the currency in another locale (I'm aware of #37, #15 and #13). When I tried to run the yarn command on master branch I got the following error:

## Yarn command output
```
yarn install v1.7.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error https://schoology.jfrog.io/schoology/api/npm/npm/weak/-/weak-1.0.1.tgz: Request failed "404 Not Found"
error https://schoology.jfrog.io/schoology/api/npm/npm/nan/-/nan-2.7.0.tgz: Request failed "404 Not Found"
error An unexpected error occurred: "https://schoology.jfrog.io/schoology/api/npm/npm/rollup/-/rollup-0.43.1.tgz: Request failed \"404 Not Found\"".
```

## yarn-error.log Trace output
```
Trace: 
  Error: https://schoology.jfrog.io/schoology/api/npm/npm/rollup/-/rollup-0.43.1.tgz: Request failed "404 Not Found"
      at Request.<anonymous> (/usr/local/Cellar/yarn/1.3.2/libexec/lib/cli.js:59356:26)
      at emitOne (events.js:116:13)
      at Request.emit (events.js:211:7)
      at Request.module.exports.Request.onRequestResponse (/usr/local/Cellar/yarn/1.3.2/libexec/lib/cli.js:123971:10)
      at emitOne (events.js:116:13)
      at ClientRequest.emit (events.js:211:7)
      at HTTPParser.parserOnIncomingClient (_http_client.js:551:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
      at TLSSocket.socketOnData (_http_client.js:440:20)
      at emitOne (events.js:116:13)
```

## Expected behavior
The expected behavior is that the yarn command would run.

## Steps to reproduce
1) Fork the repository
2) Clone the version
3) Run the command `yarn`

## Enviroment
```
$ yarn --version
1.7.0
$ node --version
v8.9.4
$ npm --version
5.6.0
```

Is there a fix for this, did I miss some step? Or should I be developing on another branch?

**Comment by ianmcnally** [comment]
Oh no, sorry! Looks like it's using a previous employer's internal registry. I'll gladly update it as soon as I can; just need to change the registry in the lockfile.

**Comment by ianmcnally** [comment]
Should be all set after d266081 on master. Apologies for the trouble! If anything else is amiss, please reach out.

**Comment by jpaulomotta** [comment]
Running yarn after your commit made it work perfectly.

Thank you @ianmcnally.
